name: flfp_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - xgboost
  - openpyxl
  - pip:
    - -r requirements.txt